amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.1
    update_min_a: 0.1

map_server:
  ros__parameters:
    yaml_filename: ""
    use_sim_time: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    max_planning_time: 5.0
    planner_plugins: ["GridBased"]

controller_server:
  ros__parameters:
    controller_frequency: 15.0
    min_vel_x: 0.05
    max_vel_x: 0.5
    min_vel_theta: 0.3
    max_vel_theta: 2.0

bt_navigator:
  ros__parameters:
    default_nav_throttle: 1.0
