slam_toolbox:
  ros__parameters:
    scan_topic: /scan
    use_sim_time: false
    resolution: 0.05
    map_file_name: ""
    provide_odom_frame: false
    publish_period_sec: 0.5
    mode: "mapping"
